default: &default
   adapter: postgresql
   enconding: unicode
   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
   url: <%= ENV['DATABASE_URL'] %>

test:
   <<: *default
   database: purchasing-power-test
   
development:
   <<: *default
   database: purchasing-power-dev

production:
  <<: *default
  