default: &default
   adapter: postgresql
   enconding: unicode
   pool: 5
   host: <%= ENV['DB_HOST'] %>
   username: <%= ENV['DB_USERNAME'] %>
   password: <%= ENV['DB_PASSWORD'] %>

development:
   <<: *default
   database: purchasing-power-dev


test:
   <<: *default
   database: purchasing-power-test

production:
   <<: *default
   database: purchasing-power
   