default: &default
   adapter: postgresql
   enconding: unicode
   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
   url: <%= ENV['DATABASE_URL'] %>

development:
   <<: *default
   database: purchasing-power-dev


test:
   <<: *default
   database: purchasing-power-test

production:
  <<: *default
  