version: '3'
services:
    scrap-purchasing-power:
        build: 
            dockerfile: Dockerfile
            context: ./scrap-purchasing-power
        image: scrap-image
        container_name: scrap-container
        ports: 
            - 3500:3500
        environment: 
            PORT: 3500
            QUANDL_API_KEY: ''
            REDIS_URL: ''
        restart: always

    react-purchasing-power:
        build: 
            dockerfile: Dockerfile
            context: ./react-purchasing-power
        image: react-image
        container_name: react-container
        ports: 
            - 3000:3000
        environment: 
            REACT_APP_SCRAP_API: http://localhost:3500
            PORT: 3000
        restart: always
        stdin_open: true
        depends_on: 
            - scrap-purchasing-power