require 'country'

country_list = [
	["VNM", "Vietnã"],
	["ARG", "Argentina"],
	["AUS", "Austrália"],
	["BRA", "Brasil"],
	["GBR", "Grã-Bretanha"],
	["CAN", "Canadá"],
	["CHL", "Chile"],
	["CHN", "China"],
	["COL", "Colômbia"],
	["CRI", "Costa Rica"],
	["CZE", "República Checa"],
	["DNK", "Dinamarca"],
	["EGY", "Egito"],
	["EUR", "área do euro"],
	["HKG", "Hong Kong"],
	["HUN", "Hungria"],
	["IND", "Índia"],
	["IDN", "Indonésia"],
	["ISR", "Israel"],
	["JPN", "Japão"],
	["LTU", "Lituânia"],
	["MYS", "Malásia"],
	["MEX", "México"],
	["NZL", "Nova Zelândia"],
	["NOR", "Noruega"],
	["PAK", "Paquistão"],
	["PER", "Peru"],
	["PHL", "Filipinas"],
	["POL", "Polônia"],
	["RUS", "Rússia"],
	["SAU", "Arábia Saudita"],
	["SIN", "Singapura"],
	["ZAF", "África do Sul"],
	["KOR", "Coreia do Sul"],
	["LKA", "Sri Lanka"],
	["SWE", "Suécia"],
	["CHE", "Suíça"],
	["ROC", "Taiwan"],
	["THA", "Tailândia"],
	["TUR", "Turquia"],
	["EAU", "EAU"],
	["UKR", "Ucrânia"],
	["USA", "Estados Unidos"],
	["URY", "Uruguai"],
	["VEN", "Venezuela"],
	["AUT", "Áustria"],
	["BEL", "Bélgica"],
	["EST", "Estónia"],
	["FIN", "Finlândia"],
	["FRA", "França"],
	["DEU", "Alemanha"],
	["GRC", "Grécia"],
	["IRL", "Irlanda"],
	["ITA", "Itália"],
	["NLD", "Países Baixos"],
	["PRT", "Portugal"],
	["ESP", "Espanha"],
	["LVA", "Letônia"]
]

country_list.each do |abbrev, name| 
	Country.find_or_create_by(abbrev: abbrev, name: name)
end